server:
  port: ${PORT:0}
spring:
  application:
    name: hr-worker
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka