server:
  port: 8001
spring:
  application:
    name: hr-worker
  datasource:
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka